version: '3.1'

services:

  db:
    image: mariadb:10.6.13
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT: root
      MARIADB_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: deneb
      MYSQL_USER: deneb
      MYSQL_PASSWORD: deneb